# Generated by Django 4.1 on 2022-08-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denounced', models.IntegerField(default=0)),
                ('born', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('state', models.CharField(choices=[('Registrado', 'Usuario normal'), ('Moderador', 'Usuario con permisos'), ('Baneado', 'Usuario baneado'), ('Eliminado', 'Usuario eliminado')], default='Registrado', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denounced', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=250)),
                ('publicationdate', models.DateTimeField()),
                ('is_public', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('Borrador', 'Borrador no publicado'), ('Publicado', 'Publicado en el sitio'), ('Eliminado', 'Publicacion eliminada')], default='Borrador', max_length=25)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.barrio')),
            ],
        ),
    ]
