# Generated by Django 4.1 on 2022-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='namebarrio',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='barrio',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='image_one',
            field=models.ImageField(blank=True, default='static/sitio/multimedias/logo.png', null=True, upload_to='static/sitio/multimedias/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='static/sitio/multimedias/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='static/sitio/multimedias/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
