# Generated by Django 4.1 on 2022-08-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_alter_customuser_barrio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='customuser',
            name='born',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='denounced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('Registrado', 'Usuario normal'), ('Moderador', 'Usuario con permisos'), ('Baneado', 'Usuario baneado'), ('Eliminado', 'Usuario eliminado')], default='Registrado', max_length=25),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='user',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
