# Generated by Django 4.1 on 2022-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_delete_usuario_customuser_born_customuser_denounced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='static/sitio/multimedias/'),
        ),
    ]
