# Generated by Django 4.1 on 2022-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_alter_publicacion_image_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.IntegerField()),
                ('user', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=250)),
                ('comentdate', models.DateTimeField()),
            ],
        ),
    ]
