# Generated by Django 4.1 on 2022-09-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
