# Generated by Django 4.1 on 2022-09-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_customuser_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_accept',
            field=models.IntegerField(default=0),
        ),
    ]
