# Generated by Django 4.1 on 2022-09-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_alter_customuser_barrio_alter_customuser_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='born',
        ),
    ]
